spring.application.name=lab9JavaSpring

spring.datasource.url=jdbc:postgresql://localhost:5432/lab9
spring.datasource.username=postgres
spring.datasource.password=postgreAdmin
spring.jpa.hibernate.ddl-auto=update

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.username=admin
spring.mongodb.password=mongoPassword123

spring.mongodb.authentication-database=admin

spring.data.mongodb.auto-index-creation=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=7d6ac60e9d9538
spring.mail.password=4516af0cf4de3c

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.profiles.active=prod

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=always