logging.level.org.example.springlab=DEBUG

spring.output.ansi.enabled=always

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=dev_db
spring.mongodb.username=admin
spring.mongodb.password=mongoPassword123
